apiVersion: batch/v1
kind: CronJob
metadata:
  name: pods-cleanup
spec:
  schedule: "20 * * * *" #every 20 minutes
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccountName: pods-cleanup
          containers:
          - name: pods-cleanup
            image: bitnami/kubectl
            imagePullPolicy: IfNotPresent
            command: ["/bin/sh","-c"]
            args: ["kubectl delete pods --field-selector status.phase=Failed --all-namespaces; kubectl delete pods --field-selector status.phase=Succeeded --all-namespaces"]
          restartPolicy: OnFailure
