apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: cleanup-pods
subjects:
- kind: ServiceAccount
  name: pods-cleanup
  namespace: default
roleRef:
  kind: ClusterRole
  name: pods-cleanup
  apiGroup: rbac.authorization.k8s.io
